// src/renderer/src/components/Menu/MenuItem.tsx
import React, { useState } from 'react'

interface MenuItemProps {
  label: string
  hotkey?: string
  shortcut?: string
  disabled?: boolean
  checkbox?: boolean
  checked?: boolean
  hasSubmenu?: boolean
  submenu?: React.ReactNode
  onClick?: () => void
}

export const MenuItem: React.FC<MenuItemProps> = ({
  label,
  hotkey,
  shortcut,
  disabled = false,
  checkbox = false,
  checked = false,
  hasSubmenu = false,
  submenu,
  onClick
}) => {
  const [showSubmenu, setShowSubmenu] = useState(false)

  // Render label with hotkey underlined
  const renderLabel = () => {
    if (!hotkey) return label

    const index = label.toLowerCase().indexOf(hotkey.toLowerCase())
    if (index === -1) return label

    return (
      <>
        {label.slice(0, index)}
        <span className="hotkey">{label[index]}</span>
        {label.slice(index + 1)}
      </>
    )
  }

  const handleClick = () => {
    if (disabled) return
    if (hasSubmenu) return
    onClick?.()
  }

  const handleMouseEnter = () => {
    if (hasSubmenu) {
      setShowSubmenu(true)
    }
  }

  const handleMouseLeave = () => {
    if (hasSubmenu) {
      setShowSubmenu(false)
    }
  }

  const classNames = [
    'win31-menu-item',
    disabled && 'disabled',
    checkbox && 'checkbox',
    checkbox && checked && 'checked',
    hasSubmenu && 'has-submenu'
  ]
    .filter(Boolean)
    .join(' ')

  return (
    <div
      className={classNames}
      onClick={handleClick}
      onMouseEnter={handleMouseEnter}
      onMouseLeave={handleMouseLeave}
    >
      {renderLabel()}
      {shortcut && <span className="shortcut">{shortcut}</span>}
      {hasSubmenu && showSubmenu && (
        <div className="win31-submenu">{submenu}</div>
      )}
    </div>
  )
}

// src/renderer/src/components/Menu/MenuItem.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'

  interface Props {
    label: string
    hotkey?: string
    shortcut?: string
    disabled?: boolean
    checkbox?: boolean
    checked?: boolean
    hasSubmenu?: boolean
    submenu?: Snippet
    onClick?: () => void
  }

  let {
    label,
    hotkey,
    shortcut,
    disabled = false,
    checkbox = false,
    checked = false,
    hasSubmenu = false,
    submenu,
    onClick
  }: Props = $props()

  let showSubmenu = $state(false)

  // Parse label with hotkey underlined
  let labelParts = $derived.by(() => {
    if (!hotkey) return { before: label, hotkey: '', after: '' }

    const index = label.toLowerCase().indexOf(hotkey.toLowerCase())
    if (index === -1) return { before: label, hotkey: '', after: '' }

    return {
      before: label.slice(0, index),
      hotkey: label[index],
      after: label.slice(index + 1)
    }
  })

  function handleClick() {
    if (disabled) return
    if (hasSubmenu) return
    onClick?.()
  }

  function handleMouseEnter() {
    if (hasSubmenu) {
      showSubmenu = true
    }
  }

  function handleMouseLeave() {
    if (hasSubmenu) {
      showSubmenu = false
    }
  }

  let classNames = $derived(
    [
      'win31-menu-item',
      disabled && 'disabled',
      checkbox && 'checkbox',
      checkbox && checked && 'checked',
      hasSubmenu && 'has-submenu'
    ]
      .filter(Boolean)
      .join(' ')
  )
</script>

<div
  class={classNames}
  onclick={handleClick}
  onmouseenter={handleMouseEnter}
  onmouseleave={handleMouseLeave}
  role="menuitem"
>
  {labelParts.before}{#if labelParts.hotkey}<span class="hotkey">{labelParts.hotkey}</span>{/if}{labelParts.after}
  {#if shortcut}
    <span class="shortcut">{shortcut}</span>
  {/if}
  {#if hasSubmenu && showSubmenu && submenu}
    <div class="win31-submenu">
      {@render submenu()}
    </div>
  {/if}
</div>
