// src/renderer/src/components/Common/Button.tsx
import React, { forwardRef, ButtonHTMLAttributes } from 'react'

interface ButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
  isDefault?: boolean
  small?: boolean
}

export const Button = forwardRef<HTMLButtonElement, ButtonProps>(
  ({ children, isDefault = false, small = false, className = '', ...props }, ref) => {
    const classes = [
      small ? 'win31-control-button' : 'win31-button',
      isDefault ? 'default' : '',
      className
    ].filter(Boolean).join(' ')

    return (
      <button ref={ref} className={classes} {...props}>
        {children}
      </button>
    )
  }
)

Button.displayName = 'Button'

// src/renderer/src/components/Common/Button.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import type { HTMLButtonAttributes } from 'svelte/elements'

  interface Props extends HTMLButtonAttributes {
    isDefault?: boolean
    small?: boolean
    children: Snippet
    ref?: HTMLButtonElement
  }

  let {
    isDefault = false,
    small = false,
    class: className = '',
    children,
    ref = $bindable(),
    ...rest
  }: Props = $props()

  let classes = $derived(
    [
      small ? 'win31-control-button' : 'win31-button',
      isDefault ? 'default' : '',
      className
    ].filter(Boolean).join(' ')
  )
</script>

<button bind:this={ref} class={classes} {...rest}>
  {@render children()}
</button>
