// src/renderer/src/components/Common/Checkbox.tsx
import React, { forwardRef, InputHTMLAttributes } from 'react'

interface CheckboxProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'type'> {
  label: string
}

export const Checkbox = forwardRef<HTMLInputElement, CheckboxProps>(
  ({ label, className = '', id, ...props }, ref) => {
    const inputId = id || `checkbox-${label.replace(/\s+/g, '-').toLowerCase()}`

    return (
      <label htmlFor={inputId} className={`win31-checkbox ${className}`}>
        <input ref={ref} type="checkbox" id={inputId} {...props} />
        <span className="checkmark" />
        <span className="label">{label}</span>
      </label>
    )
  }
)

Checkbox.displayName = 'Checkbox'

// src/renderer/src/components/Common/Checkbox.svelte
<script lang="ts">
  import type { HTMLInputAttributes } from 'svelte/elements'

  interface Props extends Omit<HTMLInputAttributes, 'type' | 'checked'> {
    label: string
    checked?: boolean
    ref?: HTMLInputElement
  }

  let { label, checked = $bindable(false), class: className = '', id, ref = $bindable(), ...rest }: Props = $props()

  let inputId = $derived(id || `checkbox-${label.replace(/\s+/g, '-').toLowerCase()}`)
</script>

<label for={inputId} class="win31-checkbox {className}">
  <input bind:this={ref} bind:checked type="checkbox" id={inputId} {...rest} />
  <span class="checkmark"></span>
  <span class="label">{label}</span>
</label>
