// src/renderer/src/components/Dialogs/ConfirmDialog.tsx
import React, { useCallback } from 'react'
import { Dialog } from './Dialog'
import { Button } from '../Common/Button'
import { useUIStore } from '@/store/uiStore'
import { QUESTION_ICON } from '@/utils/icons'

export const ConfirmDialog: React.FC = () => {
  const { dialogData, closeDialog } = useUIStore()
  const confirmOptions = dialogData.confirmOptions

  const handleConfirm = useCallback(() => {
    confirmOptions?.onConfirm()
    closeDialog()
  }, [confirmOptions, closeDialog])

  const handleCancel = useCallback(() => {
    confirmOptions?.onCancel?.()
    closeDialog()
  }, [confirmOptions, closeDialog])

  if (!confirmOptions) return null

  return (
    <Dialog title={confirmOptions.title} onClose={handleCancel} width={350}>
      <div className="win31-confirm-content">
        <img
          src={QUESTION_ICON}
          alt="?"
          className="win31-confirm-icon"
          style={{ imageRendering: 'pixelated' }}
        />
        <div className="win31-confirm-message">{confirmOptions.message}</div>
      </div>

      <div className="win31-dialog-buttons">
        <Button onClick={handleConfirm} isDefault autoFocus>
          Yes
        </Button>
        <Button onClick={handleCancel}>No</Button>
      </div>
    </Dialog>
  )
}

// src/renderer/src/components/Dialogs/ConfirmDialog.svelte
<script lang="ts">
  import Dialog from './Dialog.svelte'
  import Button from '../Common/Button.svelte'
  import { uiStore } from '@/stores'
  import { QUESTION_ICON } from '@/utils/icons'

  let confirmOptions = $derived(uiStore.dialogData.confirmOptions)

  function handleConfirm() {
    confirmOptions?.onConfirm?.()
    uiStore.closeDialog()
  }

  function handleCancel() {
    confirmOptions?.onCancel?.()
    uiStore.closeDialog()
  }
</script>

{#if confirmOptions}
  <Dialog title={confirmOptions.title} onClose={handleCancel} width={350}>
    {#snippet children()}
      <div class="win31-confirm-content">
        <img
          src={QUESTION_ICON}
          alt="?"
          class="win31-confirm-icon"
          style="image-rendering: pixelated;"
        />
        <div class="win31-confirm-message">{confirmOptions.message}</div>
      </div>

      <div class="win31-dialog-buttons">
        <Button onclick={handleConfirm} isDefault autofocus>
          {#snippet children()}Yes{/snippet}
        </Button>
        <Button onclick={handleCancel}>
          {#snippet children()}No{/snippet}
        </Button>
      </div>
    {/snippet}
  </Dialog>
{/if}
