// src/renderer/src/components/Dialogs/DialogManager.svelte
<script lang="ts">
  import { uiStore } from '@/stores'
  import NewGroupDialog from './NewGroupDialog.svelte'
  import RenameGroupDialog from './RenameGroupDialog.svelte'
  import GroupPropertiesDialog from './GroupPropertiesDialog.svelte'
  import ItemPropertiesDialog from './ItemPropertiesDialog.svelte'
  import NewUrlDialog from './NewUrlDialog.svelte'
  import SettingsDialog from './SettingsDialog.svelte'
  import AboutDialog from './AboutDialog.svelte'
  import ConfirmDialog from './ConfirmDialog.svelte'

  let activeDialog = $derived(uiStore.activeDialog)
</script>

{#if activeDialog === 'newGroup'}
  <NewGroupDialog />
{:else if activeDialog === 'renameGroup'}
  <RenameGroupDialog />
{:else if activeDialog === 'groupProperties'}
  <GroupPropertiesDialog />
{:else if activeDialog === 'newItem' || activeDialog === 'itemProperties'}
  <ItemPropertiesDialog />
{:else if activeDialog === 'newUrl'}
  <NewUrlDialog />
{:else if activeDialog === 'settings'}
  <SettingsDialog />
{:else if activeDialog === 'about'}
  <AboutDialog />
{:else if activeDialog === 'confirm'}
  <ConfirmDialog />
{/if}

// src/renderer/src/components/Dialogs/DialogManager.tsx
import React from 'react'
import { useUIStore } from '@/store/uiStore'
import { NewGroupDialog } from './NewGroupDialog'
import { RenameGroupDialog } from './RenameGroupDialog'
import { GroupPropertiesDialog } from './GroupPropertiesDialog'
import { ItemPropertiesDialog } from './ItemPropertiesDialog'
import { NewUrlDialog } from './NewUrlDialog'
import { SettingsDialog } from './SettingsDialog'
import { AboutDialog } from './AboutDialog'
import { ConfirmDialog } from './ConfirmDialog'

export const DialogManager: React.FC = () => {
  const activeDialog = useUIStore((state) => state.activeDialog)

  switch (activeDialog) {
    case 'newGroup':
      return <NewGroupDialog />
    case 'renameGroup':
      return <RenameGroupDialog />
    case 'groupProperties':
      return <GroupPropertiesDialog />
    case 'newItem':
    case 'itemProperties':
      return <ItemPropertiesDialog />
    case 'newUrl':
      return <NewUrlDialog />
    case 'settings':
      return <SettingsDialog />
    case 'about':
      return <AboutDialog />
    case 'confirm':
      return <ConfirmDialog />
    default:
      return null
  }
}
